#!/usr/bin/env python3

import sys
import os

from helpers import get_user_timeline
from analyzer import Analyzer
from termcolor import colored

N_TWEETS = 50

def main():
    # handle args
    if len(sys.argv) != 2:
        print("Usage: ./tweets screen_name")
        return 1
    else:
        screen_name = sys.argv[1]
        if screen_name[0] == "@":
            screen_name = screen_name[1:]
        
    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")

    # instantiate analyzer
    analyzer = Analyzer(positives, negatives)
        
    # retreive tweets
    tweets = get_user_timeline(screen_name, N_TWEETS)
    
    # testing
    # print("tweets retreived: {}".format(len(tweets)))
    
    # color print
    for t in tweets:
        t_score = analyzer.analyze(t)
        output_string = "{} {}".format(t_score, t)
        if t_score > 0.0:
            print(colored(output_string, "green"))
        elif t_score < 0.0:
            print(colored(output_string, "red"))
        else:
            print(colored(output_string, "yellow"))
    
    return 0
    
    
if __name__ == "__main__":
    main()